RGBLIGHT_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes

VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
TAP_DANCE_ENABLE = yes 
QMK_SETTINGS = no

KEY_OVERRIDE_ENABLE = no
GRAVE_ESC_ENABLE = yes
SPACE_CADET_ENABLE = yes
MAGIC_ENABLE = no
